### ISSUE TITLE
Demo no longer working

### ISSUE THREAD

**Issue by cah-briangantzler** [rajasegar/ember-x-tabs#10]
The demo no longer works. One issue I see is that github is spelled githuh

Not sure if there is more to it than that

**Comment by rajasegar** [comment]
Fixed now, please check

**Comment by cah-briangantzler** [comment]
The demo is now working once I corrected the url. Got to github for this repo and there is a link to the demo in the header, it has github spelled as githuh


"An Ember tab component addon with various mix of tab layout styles and theming options https://rajasegar.githuh.io/ember-x-t…"
