### ISSUE TITLE
Make Contextual Component

### ISSUE THREAD

**Issue by cah-briangantzler** [rajasegar/ember-x-tabs#4]
Have you thought about making this a contextual component instead of tying the items together by panelId and elementId?

Also possibly act as a page control (tabs but same content different data)?

I ended up playing around and did create an alternate form, (blatantly stealing your css), since usage is different, I thought creating new components would be better. Working on a pull request so  you can see what I did if you are interested.

Basic usage is as below.

- You should be able to have multiple tabs on the same page as it doesn't use element Ids.
- The data element is optional and shows a use of the control as a page control. Tabs that the pane is the same for every tab, just different data.
- Allows the ability to set the initial tab

```
{{#tab-page-control activeName="tab2" tab-style="tabs-style-topline" as | api | }}
  {{log api}}
  {{#api.tabContainer"}}
    {{#api.tab name="tab1" data="Me"}}
      Tab 1
    {{/api.tab}}
    {{#api.tab name="tab2" data="You"}}
      Tab 2 (more)
    {{/api.tab}}
  {{/api.tabContainer}}
  {{#api.contentContainer}}
    {{#api.pane name="tab1"}}
      This is pane one its very long
    {{/api.pane}}
    {{#api.pane name="tab2"}}
      This is pane two
    {{/api.pane}}
  {{/api.contentContainer}}

  Data: {{api.activeData}}

{{/tab-page-control}}
```

**Comment by bgantzler** [comment]
Ok, have redone the component, if you check my fork for the branch x-tabs (plural) you will see all the updates. You can run the dummy app, theres a link to the same page but implemented using new component. I have not created any tests yet.

Should I do a pull request for this?

Usage now is

As usual tab component
```
  {{#x-tabs tab-style="tabs-style-bar" as | xt | }}

  {{!-- tab content --}}
    {{#xt.tabs as | tabs |}}
      {{#tabs.tab name="home"}}
        <i class="icon icon-home"></i>
        <span>Home</span>
      {{/tabs.tab}}
      {{#tabs.tab name="archive"}}
        <i class="icon icon-box"></i>
        <span>Archive</span>
      {{/tabs.tab}}
      {{#tabs.tab name="analytics"}}
        <i class="icon icon-display"></i>
        <span>Analytics</span>
      {{/tabs.tab}}
      {{#tabs.tab name="settings"}}
        <i class="icon icon-tools"></i>
        <span>Settings</span>
      {{/tabs.tab}}
      {{#tabs.tab name="upload"}}
        <i class="icon icon-upload"></i>
        <span>Upload</span>
      {{/tabs.tab}}
    {{/xt.tabs}}

    {{!-- tab content --}}
    {{#xt.panes as | panes |}}
      {{#panes.pane name="home"}}
        <h1>Home</h1>
        <p>This is home content</p>
      {{/panes.pane}}
      {{#panes.pane name="archive"}}
        <h1>Archive</h1>
        <p>This is archive content</p>
      {{/panes.pane}}
      {{#panes.pane name="analytics"}}
        <h1>Analytics</h1>
        <p>This is analytics content</p>
      {{/panes.pane}}
      {{#panes.pane name="settings"}}
        <h1>Settings</h1>
        <p>This is settings content</p>
      {{/panes.pane}}
      {{#panes.pane name="upload"}}
        <h1>Upload</h1>
        <p>This is upload content</p>
      {{/panes.pane}}
    {{/xt.panes}}

  {{/x-tabs}}
```

As an additional functionality, a page control
```
  {{#x-tabs activeName="archive" tab-style="tabs-style-topline" as | xt | }}

    {{#xt.tabs as | tabs |}}
      {{#tabs.tab name="home" data=(hash name="Home data")}}
        <i class="icon icon-home"></i>
        <span>Home</span>
      {{/tabs.tab}}
      {{#tabs.tab name="archive" data=(hash name="Archive Data")}}
        <i class="icon icon-box"></i>
        <span>Archive</span>
      {{/tabs.tab}}
      {{#tabs.tab name="analytics" data=(hash name="Analytics Data")}}
        <i class="icon icon-display"></i>
        <span>Analytics</span>
      {{/tabs.tab}}
      {{#tabs.tab name="settings" data=(hash name="Settings Data")}}
        <i class="icon icon-tools"></i>
        <span>Settings</span>
      {{/tabs.tab}}
      {{#tabs.tab name="upload" data=(hash name="Upload Data")}}
        <i class="icon icon-upload"></i>
        <span>Upload</span>
      {{/tabs.tab}}

    {{/xt.tabs}}

    {{#xt.dataPane as | pane |}}
      <h1>Page Control</h1>
      <p>Data: {{pane.data.name}}</p>
    {{/xt.dataPane}}

  {{/x-tabs}}
```

**Comment by rajasegar** [comment]
@bgantzler I would love that PR, awesome job, appreciate it very much.

**Comment by bgantzler** [comment]
Great. A few questions then

1) I am not intimate with area-controls, and tried to preserve that, but does it required elementIds? Because I am no longer using elementIDs, but they could be put back if needed.
2) All the styles work by just changing the tab-style property except shape. The user is required to  do more. I could possibly pull that in but I am unfamiliar with the <svg> tag. Could you explain more what that is doing?
3) Would you be opposed to me upgrading the qunit tests to the new style?

Because I created x-tabs instead of refactoring x-tab this would not be a breaking change and users would be able to convert tabs one by one if they wished. I hope that was ok,

**Comment by rajasegar** [comment]
Thanks @bgantzler
