### ISSUE TITLE
#with  deprecation

### ISSUE THREAD

**Issue by cah-briangantzler** [rajasegar/ember-x-tabs#42]
DEPRECATION: `{{#with}}` is deprecated. If you always want the block to render, replace `{{#with}}` with `{{#let}}`. If you want to conditionally render the block, use `{{#let}}` together with `{{#if}} instead. ('ember-x-tabs/templates/components/x-tabs.hbs' @ L1:C0)  [deprecation id: ember-glimmer.with-syntax] See https://deprecations.emberjs.com/v3.x/#toc_ember-glimmer-with-syntax for more details.

**Comment by rajasegar** [comment]
Fixed in https://github.com/rajasegar/ember-x-tabs/releases/tag/v1.0.8
