### ISSUE TITLE
getWithDefault deprecation

### ISSUE THREAD

**Issue by arparthasarathi** [rajasegar/ember-x-tabs#49]
The function getWithDefault has been deprecated in the latest versions with the message below.

```Using getWithDefault has been deprecated. Instead, consider using Ember get and explicitly checking for undefined. [deprecation id: ember-metal.get-with-default] See https://deprecations.emberjs.com/v3.x#toc_ember-metal-get-with-default for more details.```

I have [created a PR](https://github.com/rajasegar/ember-x-tabs/pull/48) to replace the function with custom utility. Please  do have a look and share your thoughts. Thank you!

**Comment by rajasegar** [comment]
@arparthasarathi Sorry for the late response, since we released a new version 2.0.0, this issue is not relevant now I guess and closing it.
