### ISSUE TITLE
Fallback this deprecation

### ISSUE THREAD

**Issue by cah-briangantzler** [rajasegar/ember-x-tabs#57]
https://github.com/rajasegar/ember-x-tabs/blob/master/addon/templates/components/x-tabs.hbs#L5 for example is not using the `this` keyword.

Is this repo still being maintained that if I submit a PR this will get worked? (Sorry, last release was 2017, but I see there have been tags). Will get a PR out for this

**Comment by cah-briangantzler** [comment]
we never deprecated and removed the old component. Was hoping to not make a major change but many of the places that need `this` added should actually have `@` instead and would be more obvious if we converted the components to glimmer.

**Comment by rajasegar** [comment]
Yes, I actually started the same in the v2 branch, I will push it today, not much done so far other running ember-cli-update, appreciate any help, also fine if you can take it from there

**Comment by cah-briangantzler** [comment]
:) I had another branch that deleted those 

I was going to merge this first, as the removing of the deleted is a breaking change.

So you will have to decide if you want this on master or on a V1 branch that will then re-merge to V2.

Will def do a follow up PR that will just re-write the whole thing to modern ember

**Comment by cah-briangantzler** [comment]
https://github.com/rajasegar/ember-x-tabs/commit/8fbbff6cbdf3f82d5e29e3c7f102af5de09b1b18 this commit failed to remove the hbs files (FYI)

**Comment by cah-briangantzler** [comment]
I have a PR that will remove the rest of the files and updates the component to modern ember. Please merge this PR then I will post that one.

**Comment by rajasegar** [comment]
Merged the PR

**Comment by cah-briangantzler** [comment]
What is the purpose of the V2 branch? Since you merged a commit into master that removes some of the old components, you already have a breaking change on the main branch?

**Comment by rajasegar** [comment]
It was supposed to move to 4.x, but since you already changed the components to the new syntax I might delete the branch or repurpose the same. Closing this issue since v2.0.0 is released
