### ISSUE TITLE
semantic-release and forks

### ISSUE THREAD

**Issue by cah-brian-gantzler** [rajasegar/ember-x-tabs#94]
I have a fork of this repo, when I update and push master in my fork, it apparently runs the github actions for my fork, leading to a failed run. See here https://github.com/bgantzler/ember-x-tabs/runs/5677001987?check_suite_focus=true (hoping thats public enough you can get to it). 

I wonder what other repos are doing to protect against things like this in forks

**Comment by rajasegar** [comment]
I think we need to manually disable them as mentioned here
https://github.community/t/stop-github-actions-running-on-a-fork/17965/2
