### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by cah-brian-gantzler** [rajasegar/ember-x-tabs#97]
Could we get a 2.0.2 release that includes the commit https://github.com/rajasegar/ember-x-tabs/commit/8cb6ed2bb49cf93868790103f3bbb39e419bd3da This deprecation is preventing me from making it to ember 4.0

Thanks

**Comment by cah-brian-gantzler** [comment]
bump

**Comment by rajasegar** [comment]
done, 2.0.2 published to npm, please check whether you have the changes
